### ISSUE TITLE
Самоудаляющиеся сообщения

### ISSUE THREAD

**Issue by Albina-G** [urfu-2017/team4#149]
Флаг переходит на все диалоги
![image](https://user-images.githubusercontent.com/22474086/40268032-a4214e68-5b7f-11e8-8f5b-a3f0cf58d1eb.png)
![image](https://user-images.githubusercontent.com/22474086/40268036-b318c32e-5b7f-11e8-90aa-f7492e718e5f.png)

**Comment by KIlyaA** [comment]
А это плохо?
Или ожидалось другое поведение?

**Comment by Albina-G** [comment]
@KIlyaA  мне кажется оно должно действовать только на одном диалоге. А то такой переходишь на другой диалог, а забыл что таймер включен, и сообщения удалились
